# Generated by Django 5.0.1 on 2024-01-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_produto_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_min',
            field=models.IntegerField(),
        ),
    ]
