# Generated by Django 5.0.1 on 2024-01-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
