# Generated by Django 5.0.1 on 2024-01-15 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='celular_invalido', message='Numero de celular invalido', regex='^\\(\\d{2}\\)9\\d{4}\\d{4}$')]),
        ),
    ]
