# Generated by Django 5.0.1 on 2024-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_validacao',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
