# Generated by Django 5.0.1 on 2024-01-15 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(default='laranjeiras', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(default=0, max_length=100, validators=[django.core.validators.RegexValidator(code='cep_invalido', message='CEP invalido', regex='^\\d{5}(-\\d{3})?$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(default='Sao paulo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='complemento',
            field=models.CharField(default='apto 10', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='AM', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(default=123, max_length=5, validators=[django.core.validators.RegexValidator(code='numero_invalido', message='Numero invalido', regex='^\\d{1,5}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rua',
            field=models.CharField(default='laranjeiras', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EnderecoUsuario',
        ),
    ]
