# Generated by Django 5.0.1 on 2024-01-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_user_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(default='laranjeiras', max_length=100),
            preserve_default=False,
        ),
    ]
