# Generated by Django 5.0.1 on 2024-01-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_avaliacaouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaouser',
            name='user_email',
            field=models.CharField(max_length=50),
        ),
    ]
