# Generated by Django 5.0.1 on 2024-01-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_avaliacaouser_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
