# Generated by Django 5.0.1 on 2024-01-18 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='cpf_user',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='produtos',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='carrinho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.carrinho'),
            preserve_default=False,
        ),
    ]
