# Generated by Django 5.0.1 on 2024-01-19 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaouser',
            name='user_email',
        ),
        migrations.AddField(
            model_name='avaliacaouser',
            name='usuario',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
