# Generated by Django 5.0.1 on 2024-01-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_avaliacaouser_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaouser',
            name='usuario',
        ),
        migrations.AddField(
            model_name='avaliacaouser',
            name='user',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
