# Generated by Django 5.0.1 on 2024-01-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_avaliacaouser_usuario_avaliacaouser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaouser',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
